### ISSUE TITLE
web link for cash memory calculations

### ISSUE THREAD

**Issue by Sandy4321** [mtrempoltsev/msu_cpp_lectures#1]
can you recommend some links for fast cash memory calculations
so fastest possible, pls
spasibo

**Comment by mtrempoltsev** [comment]
Sorry, I do not know any good resources.

**Comment by Sandy4321** [comment]
so it is impossible to do cash calculations or another speed up based on memory use
you may remember in borland C++ was tiny and small memory? so tiny memory was faster but less code and data?

**Comment by mtrempoltsev** [comment]
Just try to write compact code and aim for compact data. Also remeber about read/write amplification (I mean the cache line size) and that memory jumps kills performance.
